on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
      - master

jobs:
  deploy_presentation:
    runs-on: ubuntu-latest
    name: Generate a Remark Presentation
    steps:
    - id: Generate-Presentation
      uses: rreichel3/remarkable-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        #pages-branch: pages (Default)
        #markdown-path: ./presentation.md (Default)

